#!/bin/sh

set -e

BUILD_ROOT=$HOME/vbam-build-mac

BUILD_ENV=$(cat <<'EOF'
export MACOSX_DEPLOYMENT_TARGET=10.7
export CC=clang
export CXX=clang++
export CFLAGS="-framework Carbon -arch x86_64 -Wno-unused-command-line-argument"
export CXXFLAGS="-stdlib=libc++ -framework Carbon -arch x86_64 -Wno-unused-command-line-argument"
export OBJCXXFLAGS="-stdlib=libc++ -framework Carbon -arch x86_64 -Wno-unused-command-line-argument"
export LDFLAGS="-framework Carbon -arch x86_64 -Wno-unused-command-line-argument"
EOF
)

TAR=tar

DIST_PRE_BUILD="
    libmodplug      sed -i .bak '/-mmacosx-version-min=/d' configure.ac; sed -i .bak 's/-lstdc++/-lc++/g' libmodplug.pc.in; rm -f configure
    libzmq          sed -i .bak 's/-lstdc++/-lc++/g' src/libzmq.pc.in
    ffmpeg          sed -i .bak 's/-lstdc++/-lc++/g' configure
"

. "$(dirname "$0")/../builder/core.sh"

table_line_append DIST_ARGS wxwidgets  "--with-macosx-version-min=$MACOSX_DEPLOYMENT_TARGET LDFLAGS='$LDFLAGS -stdlib=libc++'"
table_line_append DIST_ARGS ffmpeg     "--extra-ldflags='-framework CoreText'"
table_line_append DIST_ARGS libmodplug "CC=clang++ CXX=clang++"

builder "$@"
